blank_issues_enabled: false
contact_links:
  - name: 📣 Got a Suggestion?
    url: https://github.com/TeamRoboManipal25/TeamRoboManipal25/issues/new/choose
    about: Click here to share your ideas or feedback with the team!
