name: 💡 Suggestion
description: Suggest an improvement, idea, or feedback for the taskphase
title: "[Suggestion]: "
labels: [suggestion, feedback]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        👋 **Thank you for taking the time to suggest something!**
        
        Your input helps us improve the experience for everyone. Please fill out the form below to the best of your ability.

  - type: input
    id: title
    attributes:
      label: Suggestion Title
      description: A short, descriptive title for your suggestion.
      placeholder: Improve AI module explanations
    validations:
      required: true

  - type: textarea
    id: suggestion-details
    attributes:
      label: Suggestion Details
      description: Describe your suggestion in detail. Be as specific as possible.
      placeholder: |
        It would be great if we could add a short explanation on CNN and include real-life use cases to make it more intuitive.
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area of Suggestion
      description: Which week/module does your suggestion relate to?
      options:
        - General
        - Week 1: C/C++
        - Week 2: Python / GitHub
        - Week 3: AI/ML Intro
        - Week 4: Decision Trees
        - Week 5-6: OpenCV
        - Week 7-8: ROS2 / Gazebo
        - Week 9-10: Microcontrollers
        - Week 11: Final Project
    validations:
      required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes (Optional)
      description: Any extra thoughts or context you'd like to share?
      placeholder: "Feel free to include links, references, or screenshots."
    validations:
      required: false
